-- Skills tracked by user
create table skills (
  id uuid default gen_random_uuid() primary key,
  name text not null,
  category text not null default 'AI/ML',
  description text,
  status text not null default 'not_started' check (status in ('not_started', 'in_progress', 'completed')),
  progress integer default 0 check (progress >= 0 and progress <= 100),
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- Learning paths generated by Claude for each skill
create table learning_paths (
  id uuid default gen_random_uuid() primary key,
  skill_id uuid references skills(id) on delete cascade,
  total_steps integer default 0,
  created_at timestamptz default now()
);

-- Individual steps in a learning path
create table learning_steps (
  id uuid default gen_random_uuid() primary key,
  path_id uuid references learning_paths(id) on delete cascade,
  step_number integer not null,
  title text not null,
  description text not null,
  estimated_time text,
  completed boolean default false,
  resources jsonb default '[]',
  created_at timestamptz default now()
);

-- Auto-update updated_at on skills
create or replace function update_updated_at_column()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

create trigger update_skills_updated_at
  before update on skills
  for each row
  execute function update_updated_at_column();
